[arg] [0]=/HOME/scz1075/.conda/envs/kungfu/bin/python
[arg] [1]=/HOME/scz1075/.local/bin/kungfu-run
[arg] [2]=-np
[arg] [3]=2
[arg] [4]=/HOME/scz1075/.conda/envs/kungfu/bin/python3
[arg] [5]=tf_cnn_benchmarks.py
[arg] [6]=--batch_size=64
[arg] [7]=--data_format=NCHW
[arg] [8]=--model=resnet50
[arg] [9]=--optimizer=momentum
[arg] [10]=--variable_update=kungfu
[arg] [11]=--kungfu_option=sync_sgd
[arg] [12]=--nodistortions
[arg] [13]=--num_gpus=1
[arg] [14]=--num_epochs=90
[arg] [15]=--weight_decay=1e-4
[arg] [16]=--data_dir=/HOME/scz1075/run/data/tiny-imagenet-200/tfrecords
[nic] [0] lo :: 127.0.0.1/8, ::1/128
[nic] [1] enp39s0f3u1u2c2 :: 
[nic] [2] eno1 :: 10.254.24.99/22, fe80::3eec:efff:feea:6c6e/64
[nic] [3] eno2 :: 
[nic] [4] enp195s0f0 :: 
[nic] [5] enp195s0f1 :: 
[nic] [6] bond0 :: 10.254.131.42/24, fe80::eaeb:d3ff:febb:f6bd/64
[cuda-env]: CUDA_PATH=/data/apps/cuda/11.1
[cuda-env]: CUDA_HOME=/data/apps/cuda/11.1
[cuda-env]: CUDA_VISIBLE_DEVICES=0,1
[cuda-env]: CUDA_ROOT=/data/apps/cuda/11.1
[I] will parallel run 2 instances of /HOME/scz1075/.conda/envs/kungfu/bin/python3 with ["tf_cnn_benchmarks.py" "--batch_size=64" "--data_format=NCHW" "--model=resnet50" "--optimizer=momentum" "--variable_update=kungfu" "--kungfu_option=sync_sgd" "--nodistortions" "--num_gpus=1" "--num_epochs=90" "--weight_decay=1e-4" "--data_dir=/HOME/scz1075/run/data/tiny-imagenet-200/tfrecords"]
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] 2024-10-14 21:52:43.168164: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] 2024-10-14 21:52:43.168163: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] Traceback (most recent call last):
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 27, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] Traceback (most recent call last):
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 27, in <module>
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     import benchmark_cnn
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 42, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     import benchmark_cnn
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 42, in <module>
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     import datasets
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 32, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     import datasets
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/datasets.py", line 32, in <module>
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     import preprocessing
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 669
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     else:
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m]     ^
[[1;32m127.0.0.1.10000[m::[1;35mstderr[m] SyntaxError: invalid syntax
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     import preprocessing
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]   File "/data/run01/scz1075/kf-benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 669
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     else:
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m]     ^
[[1;34m127.0.0.1.10001[m::[1;35mstderr[m] SyntaxError: invalid syntax
[1;35m[E][m #<127.0.0.1.10001> exited with error: exit status 1
[1;35m[E][m #<127.0.0.1.10000> exited with error: exit status 1
[I] all 2/2 local peers finished, took 1m11.269221106s
exit on error: 2 tasks failed at 47491150019083:/data/run01/scz1075/KungFu/srcs/go/kungfu/runner/simple.go:19
